name: Geplantes Netlify-Deploy (nur bei echten Änderungen)

on:
  schedule:
    - cron: '*/5 * * * *'  # Alle 5 Minuten
  workflow_dispatch:

jobs:
  deploy-if-needed:
    runs-on: ubuntu-latest
    steps:
      - name: Repository klonen
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Holt 2 letzte Commits (für Vergleich)

      - name: Geänderte Dateien prüfen (außer streamer_config.json)
        id: check
        run: |
          CHANGED=$(git diff --name-only HEAD^ HEAD | grep -v '^data/streamer_config.json$' || true)
          echo "CHANGED=$CHANGED" >> $GITHUB_ENV
          echo "::set-output name=changed::$CHANGED"

      - name: Netlify-Deploy auslösen
        if: steps.check.outputs.changed != ''
        run: |
          echo "Änderungen erkannt – Build wird ausgelöst."
          curl -X POST -d '{}' https://api.netlify.com/build_hooks/682f54b0077b0848a16fd5b7
